name: 'Test anticalculator'

on:
  push:
    paths:
      - 'practice/anticalculator/anticalculator.py'
      - '.github/workflows/anticalculator.yaml'
  workflow_dispatch:

jobs:
  test-anticalculator:
    timeout-minutes: 1
    name: 'test-anticalculator'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/anticalculator/anticalculator_test.py
