name: 'Test bonus'

on:
  push:
    paths:
      - 'practice/bonus/bonus.py'
      - '.github/workflows/bonus.yaml'
  workflow_dispatch:

jobs:
  test-bonus:
    timeout-minutes: 1
    name: 'test-bonus'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/bonus/bonus_test.py
