name: 'Test get_or_none'

on:
  push:
    paths:
      - 'homework/conditions_and_loops/conditions.py'
      - '.github/workflows/get_or_none.yaml'
  workflow_dispatch:

jobs:
  test-get-or-none:
    timeout-minutes: 1
    name: 'test-get-or-none'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: homework
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest homework/conditions_and_loops/conditions_test.py::test_get_or_none
