name: 'Test median'

on:
  push:
    paths:
      - 'homework/conditions_and_loops/conditions.py'
      - '.github/workflows/median.yaml'
  workflow_dispatch:

jobs:
  test-median:
    timeout-minutes: 1
    name: 'test-median'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: homework
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest homework/conditions_and_loops/conditions_test.py::test_median
