name: 'Test names_to_strings'

on:
  push:
    paths:
      - 'practice/finish_me/finish_me.py'
      - '.github/workflows/names_to_strings.yaml'
  workflow_dispatch:

jobs:
  test-names-to-strings:
    timeout-minutes: 1
    name: 'test-names-to-strings'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/finish_me/finish_me_test.py::test_names_to_strings
