name: 'Test no_long_words'

on:
  push:
    paths:
      - 'practice/finish_me/finish_me.py'
      - '.github/workflows/no_long_words.yaml'
  workflow_dispatch:

jobs:
  test-no-long-words:
    timeout-minutes: 1
    name: 'test-no-long-words'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/finish_me/finish_me_test.py::test_no_long_words
