name: 'Test nothing'

on:
  push:
    paths:
      - 'homework/module/module.py'
      - '.github/workflows/nothing.yaml'
  workflow_dispatch:

jobs:
  test-nothing:
    timeout-minutes: 1
    name: 'test-nothing'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: homework
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest homework/module/module_test.py::test_nothing
