name: 'Test sum_some'

on:
  push:
    paths:
      - 'practice/lists_and_strings/lists.py'
      - '.github/workflows/sum_some.yaml'
  workflow_dispatch:

jobs:
  test-sum-some:
    timeout-minutes: 1
    name: 'test-sum-some'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/lists_and_strings/lists_test.py::test_sum_some
