name: 'Test github'

on:
  push:
    paths:
      - 'practice/request/github.py'
      - '.github/workflows/github.yaml'
  workflow_dispatch:

jobs:
  test-github:
    timeout-minutes: 1
    name: 'test-github'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest requests urllib3
      - run: |
          pytest practice/request/github_test.py
