name: 'Test random_access'

on:
  push:
    paths:
      - 'practice/basics/text.py'
      - '.github/workflows/random_access.yaml'
  workflow_dispatch:

jobs:
  test-random-access:
    timeout-minutes: 1
    name: 'test-random-access'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/basics/text_test.py::test_random_access
