name: 'Test transfer_object'

on:
  push:
    paths:
      - 'practice/transfer/transfer_object.py'
      - '.github/workflows/transfer_object.yaml'
  workflow_dispatch:

jobs:
  test-transfer-object:
    timeout-minutes: 1
    name: 'test-transfer-object'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/transfer/transfer_object_test.py
