name: 'Test apply'

on:
  push:
    paths:
      - 'practice/exercise/exercise.py'
      - '.github/workflows/apply.yaml'
  workflow_dispatch:

jobs:
  test-apply:
    timeout-minutes: 1
    name: 'test-apply'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/exercise/exercise_test.py::test_apply
