name: 'Test flatten'

on:
  push:
    paths:
      - 'practice/rprint/rprint.py'
      - '.github/workflows/flatten.yaml'
  workflow_dispatch:

jobs:
  test-flatten:
    timeout-minutes: 1
    name: 'test-flatten'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/rprint/rprint_test.py::test_flatten
