name: 'Test log_args'

on:
  push:
    paths:
      - 'practice/args/args.py'
      - '.github/workflows/log_args.yaml'
  workflow_dispatch:

jobs:
  test-log-args:
    timeout-minutes: 1
    name: 'test-log-args'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/args/args_test.py::test_log_args
